# Generated by Django 6.0.3 on 2026-03-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='minimum_stock',
            field=models.IntegerField(default=0),
        ),
    ]
