# Generated by Django 6.0.3 on 2026-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseorder_total_amount_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='inventory_received',
            field=models.BooleanField(default=False),
        ),
    ]
